# Generated by Django 5.2.17 on 2026-08-08 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Filename or custom title', max_length=255)),
                ('uploaded_video', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed/%Y/%m/%d/')),
                ('activity', models.CharField(default='Normal', max_length=100)),
                ('confidence', models.FloatField(default=0.0, help_text='Percentage confidence score')),
                ('is_suspicious', models.BooleanField(default=False)),
                ('total_frames', models.IntegerField(default=0)),
                ('sampled_frames', models.IntegerField(default=0)),
                ('fps', models.FloatField(default=30.0)),
                ('resolution', models.CharField(blank=True, default='', max_length=50)),
                ('processing_time_sec', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Detection',
                'verbose_name_plural': 'Activity Detections',
                'ordering': ['-created_at'],
            },
        ),
    ]
